# Generated by Django 2.1.2 on 2018-10-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0006_auto_20181014_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='perfiles/default.jpg', upload_to='perfiles/'),
        ),
    ]
