# Generated by Django 2.1.2 on 2018-10-23 22:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0008_auto_20181019_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(max_length=30)),
                ('value_buy', models.FloatField(blank=None, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('value_sell', models.FloatField(blank=None, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('amount', models.PositiveIntegerField(blank=None)),
                ('date', models.DateTimeField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type_asset', models.CharField(max_length=30)),
                ('total_amount', models.PositiveIntegerField(blank=None)),
                ('old_unit_value', models.FloatField(blank=None, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.RemoveField(
            model_name='asset',
            name='user',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='virtual_money',
            field=models.FloatField(blank=None, default=1000, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.AddField(
            model_name='userasset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfiles.UserAsset'),
        ),
    ]
